apiVersion: v1
kind: ConfigMap
metadata:
  name: mon-api-config
data:
  # Chaque clé devient une variable d'environnement dans le Pod
  APP_ENV: "production"
  APP_VERSION: "2.0.0"
  DB_HOST: "postgres-service"  # Nom du Service Kubernetes qui expose PostgreSQL
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
