apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-api
  template:
    metadata:
      labels:
        app: mon-api
    spec:
      containers:
      - name: mon-api
        image: mon-api:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # envFrom injecte TOUTES les clés d'un ConfigMap ou Secret comme variables d'env
        # C'est plus propre que de lister chaque variable une par une
        envFrom:
        - configMapRef:
            name: mon-api-config   # Toutes les clés du ConfigMap deviennent des env vars
        - secretRef:
            name: mon-api-secret   # Idem pour le Secret — DB_PASSWORD sera disponible