global:
  scrape_interval: 15s     # Prometheus interroge chaque cible toutes les 15s
  evaluation_interval: 15s # Fréquence d'évaluation des règles d'alerte (plus tard)

scrape_configs:
  - job_name: 'mon-api'
    static_configs:
      # Ces noms (api1, api2, api3) sont les noms des services Docker Compose
      # Docker Compose crée un réseau interne où chaque service est joignable par son nom
      # C'est exactement comme le Service Discovery de Kubernetes, mais en version simple
      - targets: ['api1:5000', 'api2:5000', 'api3:5000']
