apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  # b64enc encode automatiquement la valeur en base64 — plus besoin de le faire manuellement !
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
